services:
  server:
    image: radiot/tg-retrans:master
    hostname: tg-retrans
    restart: unless-stopped
    environment:
      # Optional. Enable debug info. Default: false
      #- DEBUG=false
      # Optional. Enable check. Default: true
      #- CHECK=true
      # Optional. Configure check URL. Default: http://icecast:8000/status-json.xsl
      #- CHECK_URL=http://icecast:8000/status-json.xsl
      # Optional. Configure check interval in seconds. Default: 60
      #- CHECK_INTERVAL=60
      # Optional. Configure source stream URL. Default: https://stream.radio-t.com
      #- STREAM_URL=https://stream.radio-t.com
      # Optional. Configure name of Telegram streaming host. Default: dc4-1.rtmp.t.me
      #- TG_SERVER=dc4-1.rtmp.t.me
      # Mandatory. Configure key for Telegram chat audio-video conference call.
      #- TG_KEY=111:AAA
    build:
      context: .
      dockerfile: Dockerfile
